apiVersion: acl.kafka.crossplane.io/v1alpha1
kind: Acl
metadata:
  name: sample-topic
spec:
  forProvider:
    resourceType: Topic
    aclPrinciple: Sample
    aclHost: "*"
    aclOperation: Any
    aclPermissionType: Any
    resourcePatternTypeFilter: Any
  providerConfigRef:
    name: example
