# { "brokers": [ "kafka-dev-0.kafka-dev-headless:9092"], "sasl": { "mechanism": "PLAIN", "username": "user", "password": "<your-password>"}}
# kubectl -n default create secret generic kafka-creds --from-file=credentials=kc.json
apiVersion: kafka.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: kafka-creds
      key: credentials
